sudo: required
language: python # Set the build language to Python

install:
- pip install mkdocs
- pip install mkdocs-material
- pip install mkdocs-awesome-pages-plugin
script:
    - mkdocs build --verbose --clean # Build a local version of the docs
deploy: # Deploy documentation to Github in the gh_pages branch
    provider: pages
    skip_cleanup: true
    github_token: $GITHUB_TOKEN
    local_dir: site
    on:
        branch: master