version: "3"

services:
  app:
    build: . 
    command: npm start
    ports:
      - "3000:3000"
    volumes:
      - .:/usr/app
    depends_on:
      - db
    links:
      - db
      
  db:
    image: 'mongo'
    container_name: MONGODB_LUCAS
    ports:
      - '27017:27017'
    volumes:
      - ./data/db:/data/db