site_name: Questmark
theme: 
    name: material
    language: 'pt'
    palette:
        primary: 'blue'

repo_name : 'Questmark'
repo_url : 'https://github.com/fga-eps-mds/2019.2-Questmark'

plugins:
    - search
    - awesome-pages
